WITH stage AS (
    SELECT
        TRIM(LISTING_ID) AS LISTING_ID,
        TRIM(SCRAPE_ID) AS SCRAPE_ID,
        TRIM(SCRAPED_DATE) AS SCRAPED_DATE,
        HOST_ID,
        TRIM(HOST_NAME) AS HOST_NAME,
        TRIM(HOST_SINCE) AS HOST_SINCE,
        TRIM(HOST_IS_SUPERHOST) AS HOST_IS_SUPERHOST,
        TRIM(HOST_NEIGHBOURHOOD) AS HOST_NEIGHBOURHOOD,
        TRIM(LISTING_NEIGHBOURHOOD) AS LISTING_NEIGHBOURHOOD,
        TRIM(PROPERTY_TYPE) AS PROPERTY_TYPE,
        TRIM(ROOM_TYPE) AS ROOM_TYPE,
        ACCOMMODATES,
        COALESCE(PRICE, 0) AS PRICE,
        TRIM(HAS_AVAILABILITY) AS HAS_AVAILABILITY,
        AVAILABILITY_30,
        NUMBER_OF_REVIEWS,
        COALESCE(REVIEW_SCORES_RATING, 0) AS REVIEW_SCORES_RATING,
        COALESCE(REVIEW_SCORES_ACCURACY, 0) AS REVIEW_SCORES_ACCURACY,
        COALESCE(REVIEW_SCORES_CLEANLINESS, 0) AS REVIEW_SCORES_CLEANLINESS,
        COALESCE(REVIEW_SCORES_CHECKIN, 0) AS REVIEW_SCORES_CHECKIN,
        COALESCE(REVIEW_SCORES_COMMUNICATION, 0) AS REVIEW_SCORES_COMMUNICATION,
        COALESCE(REVIEW_SCORES_VALUE, 0) AS REVIEW_SCORES_VALUE
    FROM RAW.facts
)

SELECT * FROM stage
